name: CI

on:
  pull_request:
  push:
    branches:
      - staging
      - trying

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly, beta, stable]

    steps:
    - uses: actions/checkout@master

    - name: Cache rustup
      uses: actions/cache@v1
      with:
        path: ~/.rustup

    - name: Cache cargo registry
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}-

    - name: Cache deps crates
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/deps
        key: ${{ runner.os }}-${{ matrix.rust }}-target-deps-${{ hashFiles('**/Cargo.toml') }}-

    - name: Cache build
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/build
        key: ${{ runner.os }}-${{ matrix.rust }}-target-build-${{ hashFiles('**/Cargo.toml') }}-

    - name: Cache build
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/.fingerprint
        key: ${{ runner.os }}-${{ matrix.rust }}-target-fingerprint-${{ hashFiles('**/Cargo.toml') }}-

    - name: Cache cargo registry (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**\Cargo.toml') }}-

    - name: Cache deps crates (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/deps
        key: ${{ runner.os }}-${{ matrix.rust }}-target-deps-${{ hashFiles('**\Cargo.toml') }}-

    - name: Cache build (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/build
        key: ${{ runner.os }}-${{ matrix.rust }}-target-build-${{ hashFiles('**\Cargo.toml') }}-

    - name: Cache build (on Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: target/debug/.fingerprint
        key: ${{ runner.os }}-${{ matrix.rust }}-target-fingerprint-${{ hashFiles('**\Cargo.toml') }}-

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --bins --tests

    - name: check unstable
      uses: actions-rs/cargo@v1
      with:
        command:  check
        args: --features unstable --all --bins --examples --tests
    - name: check bench
      uses: actions-rs/cargo@v1
      if: matrix.rust == 'nightly'
      with:
        command:  check
        args: --benches

    - name: check std only
      uses: actions-rs/cargo@v1
      with:
        command:  check
        args: --no-default-features --features std

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --features unstable

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

    - name: setup
      run: |
        rustup component add rustfmt
        test -x $HOME/.cargo/bin/mdbook || ./ci/install-mdbook.sh
        rustc --version

    - name: mdbook
      run: |
        mdbook build docs
    - name: fmt
      run: cargo fmt --all -- --check

    - name: Docs
      run: cargo doc --features docs

  # clippy_check:
  #   name: Clippy check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install rust
  #       run: rustup update beta && rustup default beta
  #     - name: Install clippy
  #       run: rustup component add clippy
  #     - name: clippy
  #       run: cargo clippy --all --features unstable
