on: [push, pull_request]

jobs:
  build_and_test:
    name: Build adn test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@master
    
    - name: Install nightly 
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: nightly
        override: true
        
    - name: check
      uses: actions-rs/cargo@v1
      with: 
        command: check --all --benches --bins --examples --tests
        
    - name: check unstable
      uses: actions-rs/cargo@v1
      with:
        command:  check --features unstable --all --benches --bins --examples --tests

    - name: tests
      uses: actions-rs/cargo@v1
      with: 
        command: test --all --doc --features unstable

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: Rust version
      run: |
        rustup default nightly
        rustup component add rustfmt
        rustc --version
        
    - name: fmt
      run: cargo fmt -- --check

    - name: Docs
      run: cargo doc --features docs,unstable
