on: [push, pull_request]

jobs:
  build_and_test:
    name: Build adn test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@master
    
    - name: Rust version
      run: |
        rustup default nightly
        rustup component add rustfmt
        rustup component add clippy
        rustc --version

    - name: build
      run: cargo build

    - name: tests
      run: cargo test --all --doc --features unstable

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: fmt
      run: cargo fmt -- --check

    - name: Docs
      run: cargo doc --features docs,unstable
