on: [push, pull_request]

jobs:
  ci:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [nightly]
        
    steps:
    - uses: actions/checkout@v1

    - name: build
      run: cargo build

    - name: tests
      run: cargo test --all --doc --features unstable

    - name: fmt
      run: cargo fmt -- --check

    - name: lint
      run: cargo clippy -- -Dwarnings

    - name: Docs
      run: cargo doc --features docs,unstable
